/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package popup;

import Config.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import smart.karyawan;

public class tambahkaryawan extends javax.swing.JFrame {

    public tambahkaryawan() {
        initComponents();
        generateEmployeeID();
        nokaryawan.setEditable(false); // Membuat field ID tidak bisa diedit
        role.removeItem(" "); // Hapus item kosong dari combo box
    }

    private void generateEmployeeID() {
        try (Connection conn = koneksi.getConnection(); 
             Statement stmt = conn.createStatement()) {
            
            String query = "SELECT id_karyawan FROM karyawan ORDER BY id_karyawan DESC LIMIT 1";
            ResultSet rs = stmt.executeQuery(query);
            
            if (rs.next()) {
                String lastID = rs.getString("id_karyawan");
                int num = Integer.parseInt(lastID.substring(2)) + 1;
                String newID = String.format("KR%03d", num);
                nokaryawan.setText(newID);
            } else {
                nokaryawan.setText("KR001");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                    "Gagal generate ID karyawan: " + e.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            nokaryawan.setText("KR001");
        }
    }
    
    private void simpanDataKaryawan() {
        // Ambil nilai dari form
        String id = nokaryawan.getText().trim();
        String nama = namakaryawan.getText().trim();
        String noHP = nohp.getText().trim();
        String passwordText = new String(password.getPassword());
        String roleText = role.getSelectedItem().toString();
        String rfidText = rfid.getText().trim();
        
        // Validasi input
        if (nama.isEmpty() || noHP.isEmpty() || passwordText.isEmpty() || rfidText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Semua kolom harus diisi!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Validasi nomor HP harus angka
            int noTelp = Integer.parseInt(noHP);
            
            // Query insert
            String query = "INSERT INTO karyawan (id_karyawan, nama_karyawan, no_telp, password, role, RFID) " +
                          "VALUES (?, ?, ?, ?, ?, ?)";
            
            Connection konek = koneksi.getConnection();
            PreparedStatement pst = konek.prepareStatement(query);
            
            // Set parameter dengan variabel yang benar
            pst.setString(1, id);
            pst.setString(2, nama);
            pst.setInt(3, noTelp);
            pst.setString(4, passwordText);
            pst.setString(5, roleText);
            pst.setString(6, rfidText);
            
            // Eksekusi query
            int hasil = pst.executeUpdate();
            
            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, 
                        "Data karyawan berhasil disimpan!", 
                        "Sukses", 
                        JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
                
                // Refresh tabel karyawan di form utama
                karyawan formKaryawan = new karyawan();
                formKaryawan.loadDataToTable();
                
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Gagal menyimpan data karyawan.", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
            }
            
            konek.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                    "Nomor HP harus berupa angka!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                    "Error: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nokaryawan = new javax.swing.JTextField();
        namakaryawan = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        rfid = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        role = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nokaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nokaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(nokaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 300, -1));

        namakaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namakaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(namakaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 300, -1));

        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });
        getContentPane().add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 310, -1));

        rfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfidActionPerformed(evt);
            }
        });
        getContentPane().add(rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 290, -1));

        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 393, 170, 30));

        password.setText("jPasswordField1");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 300, -1));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Karyawan", " " }));
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TAMBAH KARYAWAN V2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nokaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nokaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nokaryawanActionPerformed

    private void namakaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namakaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namakaryawanActionPerformed

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpActionPerformed

    private void rfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfidActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        simpanDataKaryawan();
    }//GEN-LAST:event_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahkaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namakaryawan;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField nokaryawan;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField rfid;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
