/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smart;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;


/**
 *
 * @author acer
 */
public class transaksi extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private static int counter = 1;
    public transaksi() {
        initComponents();
         customizeTable();
        makeButtonTransparent(bttndashboard);
        makeButtonTransparent(btn_restok);
        makeButtonTransparent(btn_karyawan);
        makeButtonTransparent(btn_logout);
        makeButtonTransparent(btn_laporan);
        makeButtonTransparent(btn_batalkan);
        makeButtonTransparent(btn_bayar);
        makeButtonTransparent(btn_cetak);
        makeButtonTransparent(btn_simpan);
        qty.setOpaque(false);
        qty.setBackground(new Color(0, 0, 0, 0));
        No_nota.setOpaque(false);
        No_nota.setBackground(new Color(0, 0, 0, 0));
        namabrg.setOpaque(false);
        namabrg.setBackground(new Color(0, 0, 0, 0));
        NoBarang.setOpaque(false);
        NoBarang.setBackground(new Color(0, 0, 0, 0));
        hargastuan.setOpaque(false);
        hargastuan.setBackground(new Color(0, 0, 0, 0));
        totalharga.setOpaque(false);
        totalharga.setBackground(new Color(0, 0, 0, 0));
        bayar.setOpaque(false);
        bayar.setBackground(new Color(0, 0, 0, 0));
        kembalian.setOpaque(false);
        kembalian.setBackground(new Color(0, 0, 0, 0));
        Kategori.setOpaque(false);
        Kategori.setBackground(new Color(0, 0, 0, 0));
        
        
        No_nota.setText(generateNota());
    }
    
    private void makeButtonTransparent(JButton button) {
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
    }
    
    private String generateNota() {
    return "Nota-" + String.format("%04d", counter++);
}
    
     private void customizeTable() {
         JTableHeader header = jTable1.getTableHeader();
         
         header.setFont(new Font("Inter", Font.BOLD, 11));
         
         header.setForeground(Color.WHITE); 
         
         header.setOpaque(false);
         
         jTable1.setFont(new Font("Arial", Font.PLAIN, 10));
         
         jTable1.setRowHeight(30); 
         
         jTable1.setShowGrid(true); 
         
         jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
         
         jTable1.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
         
         jTable1.setSelectionBackground(new Color(25, 25, 25)); 
         jTable1.setSelectionForeground(Color.WHITE); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_logout = new javax.swing.JButton();
        btn_karyawan = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();
        btn_batalkan = new javax.swing.JButton();
        btn_restok = new javax.swing.JButton();
        kembalian = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        bttndashboard = new javax.swing.JButton();
        namabrg = new javax.swing.JTextField();
        NoBarang = new javax.swing.JTextField();
        No_nota = new javax.swing.JTextField();
        hargastuan = new javax.swing.JTextField();
        totalharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        qty = new javax.swing.JTextField();
        Kategori = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 160, 30));

        btn_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_karyawanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 160, 30));

        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 160, 30));
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 630, 230, 40));
        getContentPane().add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 560, 230, 40));
        getContentPane().add(btn_batalkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, 230, 40));

        btn_restok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restokActionPerformed(evt);
            }
        });
        getContentPane().add(btn_restok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 30));

        kembalian.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        kembalian.setBorder(null);
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 630, 200, 50));

        bayar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bayar.setBorder(null);
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 200, 50));

        bttndashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttndashboardActionPerformed(evt);
            }
        });
        getContentPane().add(bttndashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 30));

        namabrg.setBorder(null);
        namabrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabrgActionPerformed(evt);
            }
        });
        getContentPane().add(namabrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 200, 30));

        NoBarang.setBorder(null);
        NoBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBarangActionPerformed(evt);
            }
        });
        getContentPane().add(NoBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 126, 200, 30));

        No_nota.setBorder(null);
        No_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_notaActionPerformed(evt);
            }
        });
        getContentPane().add(No_nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 190, 30));

        hargastuan.setBorder(null);
        hargastuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargastuanActionPerformed(evt);
            }
        });
        getContentPane().add(hargastuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 200, 30));

        totalharga.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalharga.setBorder(null);
        totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhargaActionPerformed(evt);
            }
        });
        getContentPane().add(totalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 200, 50));

        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id barang", "Nama barang", "Harga barang", "QTY"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 760, 270));

        qty.setBorder(null);
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 190, 30));

        Kategori.setBorder(null);
        Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriActionPerformed(evt);
            }
        });
        getContentPane().add(Kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 200, 30));
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 107, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Transaksi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void No_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_No_notaActionPerformed

    private void NoBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoBarangActionPerformed

    private void namabrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabrgActionPerformed

    private void hargastuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargastuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargastuanActionPerformed

    private void bttndashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttndashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttndashboardActionPerformed

    private void totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalhargaActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KategoriActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_restokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_restokActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_karyawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
                FlatLightLaf.setup();
        UIManager.put("TableHeader.background", Color.BLACK);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kategori;
    private javax.swing.JTextField NoBarang;
    private javax.swing.JTextField No_nota;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btn_batalkan;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_karyawan;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_restok;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton bttndashboard;
    private javax.swing.JTextField hargastuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField namabrg;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables
}
